baseURL: "https://hieu6.github.io/"
languageCode: "en-us"
title: "hieu's blog"
theme: archie
copyright: © 2021 hieu
paginate: 3

permalinks: 
  post: "/:slug/"

params:
  mode: "auto"    # color-mode → light,dark or auto
  subtitle: |
    Hello! I'm hieu. You've found my collection of curiosities and explorations. 
    > Current interests:
    
    * data analytics (SQL, Python-curious)
    * Jamstack (Hugo, HTML/CSS, JS-curious)
    * culture, behavior psychology, communication, relationships
    * sociology, philosophy, poetry, neuroscience, nutrition & exercise
    * mission & purpose, writing, self-management, principled living

menu:
  main:
  - identifier: blog # must match section name
    name: blog # menu link text
    url: /blog/
    weight: -110
  - identifier: notes
    name: notes
    url: /notes/
    weight: -100
  - identifier: tags
    name: tags
    url: /tags/
    weight: 100

# GH Action from GH Marketplace for hugo (?)
- name: Hugo setup
  uses: peaceiris/actions-hugo@v2.4.13
