baseURL: "http://example.org/"
languageCode: "en-us"
title: "hieu's blog"
theme: archie
copyright: © 2021 hieu

params:
  mode: "auto"    # color-mode → light,dark or auto
  subtitle: "Hello! I'm hieu. You've found my collection of curiosities and explorations."

menu:
  main:
  - identifier: blog # must match section name
    name: blog # menu link text
    url: /blog/
    weight: -110
  - identifier: notes
    name: notes
    url: /notes/
    weight: -100
  - identifier: tags
    name: tags
    url: /tags/
    weight: 100
  - identifier: about
    name: about
    url: /about/
    file: content/about.md
    weight: 110